package io.agrest.cayenne.cayenne.main.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.property.EntityProperty;
import org.apache.cayenne.exp.property.NumericProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.StringProperty;

import io.agrest.cayenne.cayenne.main.E34;

/**
 * Class _E35 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _E35 extends BaseDataObject {

    private static final long serialVersionUID = 1L;

    public static final String ID_PK_COLUMN = "id";

    public static final NumericProperty<Integer> RANKING = PropertyFactory.createNumeric("ranking", Integer.class);
    public static final StringProperty<String> SEASON = PropertyFactory.createString("season", String.class);
    public static final EntityProperty<E34> E34 = PropertyFactory.createEntity("e34", E34.class);

    protected Integer ranking;
    protected String season;

    protected Object e34;

    public void setRanking(Integer ranking) {
        beforePropertyWrite("ranking", this.ranking, ranking);
        this.ranking = ranking;
    }

    public Integer getRanking() {
        beforePropertyRead("ranking");
        return this.ranking;
    }

    public void setSeason(String season) {
        beforePropertyWrite("season", this.season, season);
        this.season = season;
    }

    public String getSeason() {
        beforePropertyRead("season");
        return this.season;
    }

    public void setE34(E34 e34) {
        setToOneTarget("e34", e34, true);
    }

    public E34 getE34() {
        return (E34)readProperty("e34");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "ranking":
                return this.ranking;
            case "season":
                return this.season;
            case "e34":
                return this.e34;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "ranking":
                this.ranking = (Integer)val;
                break;
            case "season":
                this.season = (String)val;
                break;
            case "e34":
                this.e34 = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.ranking);
        out.writeObject(this.season);
        out.writeObject(this.e34);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.ranking = (Integer)in.readObject();
        this.season = (String)in.readObject();
        this.e34 = in.readObject();
    }

}
